#!/usr/bin/python
import datetime

# NOTE: THIS IS FOR INITIAL TESTING ONLY
# run test.py inside of PHSMDataCollector_module
import PHSMDataCollector_module.main as data_collector

# Get the current date and time
now = datetime.datetime.now()
data_collector.main()
