#!/usr/bin/python
import datetime

# NOTE: THIS IS FOR INITIAL TESTING ONLY
# run test.py inside of data_collector
from data_collector import collector

# Get the current date and time
now = datetime.datetime.now()
try:
    # Run data collector module
    collector.main()
    # Run trained ML model
    # Save the results in a json file
    # Send the results to the database
except:
    Exception("Preprocessesing failed see data logs for more details")