#!/usr/bin/python
import datetime

# NOTE: THIS IS FOR INITIAL TESTING ONLY
# run test.py inside of data_collector
import data_collector as collector

# Get the current date and time
now = datetime.datetime.now()
collector.main()
