#!/usr/bin/python
import datetime

# NOTE: THIS IS FOR INITIAL TESTING ONLY
# run test.py inside of data_collector
from data_collector import main

# Get the current date and time
now = datetime.datetime.now()
main.main()
