version: "3.8"
services:
  api:
    build: ./alamAPI
    ports:
      - 8000:8000
    env_file:
      - db.env
  mongo_db:
    image: mongo:4.0
    ports:
      - 27017:27017
    volumes:
      - smptf:/data/db
    env_file:
      - db.env
  preprocessor:
    build: ./preprocessor
    env_file:
      - preprocessor.env
    volumes:
      - smptf:/data/db
volumes:
  smptf: 